---
# tasks file for ospatch

- name: Install epel-release
  package:
    name: epel-release
    state: present

- name: Install other packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - iotop
    - iftop
